{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeMapIcon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"markerId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"removeMapIcon(markerId:)","modules":[{"name":"iNaviNavigationSdk"}],"roleHeading":"Instance Method","externalID":"s:18iNaviNavigationSdk15InaviControllerC13removeMapIcon8markerIdySS_tF","symbolKind":"method"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIcon(markerId:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"abstract":[{"text":"Removes a marker added to the map using its identifier ([markerId]).","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeMapIcon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"markerId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"markerId","content":[{"inlineContent":[{"type":"text","text":"The ID of the marker to remove."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method deletes the corresponding marker from the map using the internal identifier (ID)"},{"type":"text","text":" "},{"type":"text","text":"of the marker options used in the previous [addMapIcon] call."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/removemapicon(markerid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","title":"iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InaviController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","role":"symbol","kind":"symbol","title":"InaviController","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/removeMapIcon(markerId:)":{"abstract":[{"type":"text","text":"Removes a marker added to the map using its identifier ([markerId])."}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIcon(markerId:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeMapIcon"},{"kind":"text","text":"("},{"kind":"externalParam","text":"markerId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"kind":"symbol","title":"removeMapIcon(markerId:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/removemapicon(markerid:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"InaviController","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","op":"replace"},{"value":[{"text":"InaviController","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"InaviController"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}