{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The zoom level value to set.","type":"text"}],"type":"paragraph"}],"name":"level"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Sets the map zoom level."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/setmaplevel(level:)"]}],"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapLevel(level:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"s:18iNaviNavigationSdk15InaviControllerC11setMapLevel5levelySi_tF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapLevel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"level","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"setMapLevel(level:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"iNaviNavigationSdk"}],"symbolKind":"method"},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","kind":"symbol","abstract":[],"role":"symbol","title":"InaviController","navigatorTitle":[{"kind":"identifier","text":"InaviController"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"abstract":[],"kind":"symbol","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapLevel(level:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Sets the map zoom level."}],"title":"setMapLevel(level:)","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapLevel(level:)","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmaplevel(level:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"InaviController","op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title"},{"value":[{"kind":"identifier","text":"InaviController"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments"},{"value":[{"kind":"identifier","text":"InaviController"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle"}]}]}