{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"abstract":[{"text":"Sets the map click event listener.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapClickListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"text":"InvCoordinate","preciseIdentifier":"s:18iNaviNavigationSdk13InvCoordinateV","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinate","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":"Closure to handle map click events with coordinate information."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"Use this to receive information about the point clicked by the user on the map.","type":"text"},{"text":" ","type":"text"},{"text":"The latitude and longitude coordinates of the clicked location are delivered.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/setmapclicklistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","title":"setMapClickListener(listener:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapClickListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"InvCoordinate","preciseIdentifier":"s:18iNaviNavigationSdk13InvCoordinateV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"iNaviNavigationSdk"}],"externalID":"s:18iNaviNavigationSdk15InaviControllerC19setMapClickListener8listeneryyAA13InvCoordinateVc_tF"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapClickListener(listener:)"},"kind":"symbol","sections":[],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapClickListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapClickListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"InvCoordinate","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk13InvCoordinateV"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapclicklistener(listener:)","title":"setMapClickListener(listener:)","role":"symbol","abstract":[{"text":"Sets the map click event listener.","type":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapClickListener(listener:)","kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"navigatorTitle":[{"text":"InaviController","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","title":"InaviController","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvCoordinate":{"title":"InvCoordinate","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinate","url":"\/documentation\/inavinavigationsdk\/invcoordinate","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvCoordinate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvCoordinate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","op":"replace","value":"InaviController"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","op":"replace","value":[{"text":"InaviController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","op":"replace","value":[{"text":"InaviController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}