{"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InaviController","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","preciseIdentifier":"c:@M@iNaviNavigationSdk@objc(cs)InaviController"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/shared","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","title":"shared","modules":[{"name":"iNaviNavigationSdk"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"shared","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@iNaviNavigationSdk@objc(cs)InaviController","kind":"typeIdentifier","text":"InaviController"}],"externalID":"c:@M@iNaviNavigationSdk@objc(cs)InaviController(cpy)shared"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller\/shared"]}],"sections":[],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/shared":{"kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"title":"shared","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/shared","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@iNaviNavigationSdk@objc(cs)InaviController","text":"InaviController","kind":"typeIdentifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/shared","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"navigatorTitle":[{"text":"InaviController","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","title":"InaviController","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"shared"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@iNaviNavigationSdk@objc(cs)InaviController","kind":"typeIdentifier","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","text":"InaviController"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shared"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1shared\/title","value":"shared","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","value":"InaviController","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","value":[{"text":"InaviController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","value":[{"text":"InaviController","kind":"identifier"}],"op":"replace"}]}]}