{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MLNMapViewDelegate.mapViewDidFailLoadingMap(_:withError:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfailloadingmap(_:witherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfailloadingmap(_:witherror:)"]}],"metadata":{"title":"mapViewDidFailLoadingMap(_:withError:)","modules":[{"name":"iNaviNavigationSdk"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"mapViewDidFailLoadingMap:withError:","kind":"identifier"}],"extendedModule":"iNaviNavigationSdk","externalID":"c:@CM@iNaviNavigationSdk@objc(cs)InvMapView(im)mapViewDidFailLoadingMap:withError:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidFailLoadingMap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}]},"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFailLoadingMap(_:withError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidFailLoadingMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier","text":"MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapViewDidFailLoadingMap(_:withError:)":{"type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFailLoadingMap(_:withError:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapViewDidFailLoadingMap","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mapViewDidFailLoadingMap:withError:","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfailloadingmap(_:witherror:)","abstract":[],"title":"mapViewDidFailLoadingMap(_:withError:)","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","title":"iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/inavinavigationsdk\/invmapview","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","navigatorTitle":[{"text":"InvMapView","kind":"identifier"}],"title":"InvMapView","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mapViewDidFailLoadingMap:withError:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mapViewDidFailLoadingMap:withError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapViewDidFailLoadingMap:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier","text":"MLNMapView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mapViewDidFailLoadingMap:withError:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFailLoadingMap(_:withError:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mapViewDidFailLoadingMap:withError:","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFailLoadingMap(_:withError:)\/fragments","op":"replace"},{"value":"InvMapView","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","op":"replace"},{"value":[{"text":"InvMapView","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"InvMapView"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","op":"replace"}]}]}