{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFinishRenderingMap(_:fullyRendered:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"sections":[],"metadata":{"modules":[{"name":"iNaviNavigationSdk"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier","text":"MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fullyRendered"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"mapViewDidFinishRenderingMap:fullyRendered:"}],"title":"mapViewDidFinishRenderingMap(_:fullyRendered:)","symbolKind":"method","externalID":"c:@CM@iNaviNavigationSdk@objc(cs)InvMapView(im)mapViewDidFinishRenderingMap:fullyRendered:","extendedModule":"iNaviNavigationSdk","role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fullyRendered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfinishrenderingmap(_:fullyrendered:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfinishrenderingmap(_:fullyrendered:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MLNMapViewDelegate.mapViewDidFinishRenderingMap(_:fullyRendered:)"},{"type":"text","text":"."}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapViewDidFinishRenderingMap(_:fullyRendered:)":{"kind":"symbol","navigatorTitle":[{"text":"mapViewDidFinishRenderingMap:fullyRendered:","kind":"identifier"}],"title":"mapViewDidFinishRenderingMap(_:fullyRendered:)","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfinishrenderingmap(_:fullyrendered:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapViewDidFinishRenderingMap","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"fullyRendered","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFinishRenderingMap(_:fullyRendered:)","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"title":"InvMapView","url":"\/documentation\/inavinavigationsdk\/invmapview","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvMapView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mapViewDidFinishRenderingMap:fullyRendered:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap:fullyRendered:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullyRendered:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"fullyRendered"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mapViewDidFinishRenderingMap:fullyRendered:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFinishRenderingMap(_:fullyRendered:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap:fullyRendered:"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFinishRenderingMap(_:fullyRendered:)\/fragments","op":"replace"},{"value":"InvMapView","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"InvMapView"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"InvMapView"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}