{"sections":[],"metadata":{"roleHeading":"Instance Method","extendedModule":"iNaviNavigationSdk","modules":[{"name":"iNaviNavigationSdk"}],"externalID":"c:@CM@iNaviNavigationSdk@objc(cs)InvMapView(im)mapView:regionIsChangingWithReason:","title":"mapView(_:regionIsChangingWith:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"mapView:regionIsChangingWithReason:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"regionIsChangingWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MLNCameraChangeReason","text":"MLNCameraChangeReason","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionIsChangingWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLNCameraChangeReason","preciseIdentifier":"c:@E@MLNCameraChangeReason"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionIsChangingWith:)"},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regionischangingwith:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regionischangingwith:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"MLNMapViewDelegate.mapView(_:regionIsChangingWith:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","title":"iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:regionIsChangingWith:)":{"url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regionischangingwith:)","navigatorTitle":[{"kind":"identifier","text":"mapView:regionIsChangingWithReason:"}],"type":"topic","kind":"symbol","title":"mapView(_:regionIsChangingWith:)","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionIsChangingWith:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"regionIsChangingWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MLNCameraChangeReason","text":"MLNCameraChangeReason","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/inavinavigationsdk\/invmapview","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","navigatorTitle":[{"text":"InvMapView","kind":"identifier"}],"title":"InvMapView","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mapView:regionIsChangingWithReason:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mapView:regionIsChangingWithReason:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"regionIsChangingWithReason:"},{"kind":"text","text":"("},{"text":"MLNCameraChangeReason","kind":"typeIdentifier","preciseIdentifier":"c:@E@MLNCameraChangeReason"},{"text":") ","kind":"text"},{"text":"reason","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"mapView:regionIsChangingWithReason:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionIsChangingWith:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mapView:regionIsChangingWithReason:","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionIsChangingWith:)\/fragments"},{"op":"replace","value":"InvMapView","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"InvMapView"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments"},{"op":"replace","value":[{"text":"InvMapView","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}