{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"MLNMapViewDelegate.mapView(_:didFinishLoading:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:didfinishloading:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:didfinishloading:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"mapView(_:didFinishLoading:)","role":"symbol","extendedModule":"iNaviNavigationSdk","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView"},{"text":", ","kind":"text"},{"text":"didFinishLoading","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLNStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNStyle"},{"text":")","kind":"text"}],"modules":[{"name":"iNaviNavigationSdk"}],"externalID":"c:@CM@iNaviNavigationSdk@objc(cs)InvMapView(im)mapView:didFinishLoadingStyle:","symbolKind":"method","navigatorTitle":[{"text":"mapView:didFinishLoadingStyle:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:didFinishLoading:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mapView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLoading","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MLNStyle","preciseIdentifier":"c:objc(cs)MLNStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","kind":"symbol","role":"symbol","title":"InvMapView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvMapView"}],"navigatorTitle":[{"kind":"identifier","text":"InvMapView"}],"type":"topic","url":"\/documentation\/inavinavigationsdk\/invmapview"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"kind":"symbol","type":"topic","role":"collection","title":"iNaviNavigationSdk","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"url":"\/documentation\/inavinavigationsdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:didFinishLoading:)":{"abstract":[],"title":"mapView(_:didFinishLoading:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:didFinishLoading:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNMapView"},{"text":", ","kind":"text"},{"text":"didFinishLoading","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLNStyle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MLNStyle"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mapView:didFinishLoadingStyle:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:didfinishloading:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"mapView:didFinishLoadingStyle:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:didFinishLoadingStyle:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"mapView:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mapView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFinishLoadingStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNStyle","text":"MLNStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","value":"InvMapView","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","value":[{"kind":"identifier","text":"InvMapView"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","value":[{"text":"InvMapView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:didFinishLoading:)\/title","value":"mapView:didFinishLoadingStyle:","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:didFinishLoading:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:didFinishLoadingStyle:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}