{"topicSections":[{"generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:didFinishLoading:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionDidChangeWith:animated:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionIsChangingWith:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFailLoadingMap(_:withError:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFinishRenderingMap(_:fullyRendered:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"kind":"article","variants":[{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mlnmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/inavinavigationsdk\/invmapview\/mlnmapviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/MLNMapViewDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"iNaviNavigationSdk"}],"role":"collectionGroup","roleHeading":"API Collection","title":"MLNMapViewDelegate Implementations"},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:regionIsChangingWith:)":{"url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regionischangingwith:)","navigatorTitle":[{"kind":"identifier","text":"mapView:regionIsChangingWithReason:"}],"type":"topic","kind":"symbol","title":"mapView(_:regionIsChangingWith:)","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionIsChangingWith:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)MLNMapView","text":"MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"regionIsChangingWith","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@MLNCameraChangeReason","text":"MLNCameraChangeReason","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/inavinavigationsdk\/invmapview","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","navigatorTitle":[{"text":"InvMapView","kind":"identifier"}],"title":"InvMapView","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:regionDidChangeWith:animated:)":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"regionDidChangeWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MLNCameraChangeReason","preciseIdentifier":"c:@E@MLNCameraChangeReason"},{"kind":"text","text":", "},{"kind":"externalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionDidChangeWith:animated:)","title":"mapView(_:regionDidChangeWith:animated:)","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:regiondidchangewith:animated:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mapView:regionDidChangeWithReason:animated:"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","title":"iNaviNavigationSdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapView(_:didFinishLoading:)":{"title":"mapView(_:didFinishLoading:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"mapView:didFinishLoadingStyle:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishLoading","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MLNStyle","preciseIdentifier":"c:objc(cs)MLNStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapview(_:didfinishloading:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:didFinishLoading:)","role":"symbol","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapViewDidFinishRenderingMap(_:fullyRendered:)":{"role":"symbol","type":"topic","url":"\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfinishrenderingmap(_:fullyrendered:)","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFinishRenderingMap(_:fullyRendered:)","title":"mapViewDidFinishRenderingMap(_:fullyRendered:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapViewDidFinishRenderingMap"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fullyRendered"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"mapViewDidFinishRenderingMap:fullyRendered:"}],"kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/mapViewDidFailLoadingMap(_:withError:)":{"type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFailLoadingMap(_:withError:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapViewDidFailLoadingMap","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MLNMapView","preciseIdentifier":"c:objc(cs)MLNMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"mapViewDidFailLoadingMap:withError:","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invmapview\/mapviewdidfailloadingmap(_:witherror:)","abstract":[],"title":"mapViewDidFailLoadingMap(_:withError:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:didFinishLoading:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionDidChangeWith:animated:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapView(_:regionIsChangingWith:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFailLoadingMap(_:withError:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/mapViewDidFinishRenderingMap(_:fullyRendered:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"mapView:regionIsChangingWithReason:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionIsChangingWith:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:regionIsChangingWithReason:"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionIsChangingWith:)\/fragments","op":"replace"},{"value":"InvMapView","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","op":"replace"},{"value":[{"text":"InvMapView","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"InvMapView"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","op":"replace"},{"value":"mapView:regionDidChangeWithReason:animated:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionDidChangeWith:animated:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"mapView:regionDidChangeWithReason:animated:","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:regionDidChangeWith:animated:)\/fragments","op":"replace"},{"value":"mapView:didFinishLoadingStyle:","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:didFinishLoading:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapView:didFinishLoadingStyle:"}],"op":"replace","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapView(_:didFinishLoading:)\/fragments"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFinishRenderingMap(_:fullyRendered:)\/title","value":"mapViewDidFinishRenderingMap:fullyRendered:","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFinishRenderingMap(_:fullyRendered:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mapViewDidFinishRenderingMap:fullyRendered:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFailLoadingMap(_:withError:)\/title","value":"mapViewDidFailLoadingMap:withError:","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView~1mapViewDidFailLoadingMap(_:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapViewDidFailLoadingMap:withError:"}],"op":"replace"}]}]}