{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/invmapview\/updatecarlocation(longitude:latitude:angle:)"]}],"metadata":{"title":"updateCarLocation(longitude:latitude:angle:)","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"iNaviNavigationSdk"}],"externalID":"s:18iNaviNavigationSdk10InvMapViewC17updateCarLocation9longitude8latitude5angleySd_SdSitF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCarLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"latitude","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"angle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateCarLocation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"longitude","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"angle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/updateCarLocation(longitude:latitude:angle:)"},"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView"]]},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"title":"InvMapView","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"navigatorTitle":[{"text":"InvMapView","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","role":"symbol","abstract":[],"url":"\/documentation\/inavinavigationsdk\/invmapview"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView/updateCarLocation(longitude:latitude:angle:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCarLocation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"angle"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"updateCarLocation(longitude:latitude:angle:)","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/invmapview\/updatecarlocation(longitude:latitude:angle:)","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView\/updateCarLocation(longitude:latitude:angle:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"abstract":[],"kind":"symbol","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","url":"\/documentation\/inavinavigationsdk","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","op":"replace","value":"InvMapView"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","op":"replace","value":[{"kind":"identifier","text":"InvMapView"}]},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","op":"replace","value":[{"text":"InvMapView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}