{"hierarchy":{"paths":[[]]},"sections":[],"metadata":{"symbolKind":"module","roleHeading":"Framework","modules":[{"name":"iNaviNavigationSdk"}],"role":"collection","title":"iNaviNavigationSdk","externalID":"iNaviNavigationSdk"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/AtomicUInt","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSimpleSearchBar"],"generated":true},{"title":"Structures","generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvAddress","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvAddressRanges","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBoundingBox","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBrand","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCategory","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvChargingPark","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvClassification","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvConnector","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinate","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvDataSourceInfo","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvDataSources","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvEntryPoint","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeocode","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeometryInfo","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvIntersectionDetail","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapCode","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapMarkerOption","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvNameLocale","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvNaviLocation","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvOpeningHours","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvPoi","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvQueryIntent","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvQueryIntentDetails","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReqSearch","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocode","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocodeAddress","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvRoutePtItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchItem","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchResult","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSummary","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimePoint","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimeRange","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimeZoneInfo","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvViewport","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/RelatedPoi"],"anchor":"Structures"},{"title":"Variables","generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionNumber","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionString"],"anchor":"Variables"},{"title":"Type Aliases","generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBottomEventListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinateListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeocodingListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvInitListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvLonLatListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapMoveListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocodingListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvRouteListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchListener","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvStatusListener"],"anchor":"Type-Aliases"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/GeocodingStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InitStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBottomBtnEvent","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapRouteColor","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapTheme","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapViewMode","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReRouteType","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchResultType","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvUIComponent","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapModeStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapMoveStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ReverseGeocodingStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/RouteStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/SearchStatus","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ShapeIDHelper"],"anchor":"Enumerations"},{"title":"Extended Modules","generated":true,"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ObjectiveC"],"anchor":"Extended-Modules"}],"kind":"symbol","references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvOpeningHours":{"url":"\/documentation\/inavinavigationsdk\/invopeninghours","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvOpeningHours","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvOpeningHours","kind":"identifier"}],"navigatorTitle":[{"text":"InvOpeningHours","kind":"identifier"}],"title":"InvOpeningHours","role":"symbol","type":"topic","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvCoordinateListener":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvCoordinateListener"}],"navigatorTitle":[{"kind":"identifier","text":"InvCoordinateListener"}],"url":"\/documentation\/inavinavigationsdk\/invcoordinatelistener","title":"InvCoordinateListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinateListener","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvReverseGeocode":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invreversegeocode","abstract":[{"type":"text","text":"Reverse geocoding response structure."}],"title":"InvReverseGeocode","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvReverseGeocode"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvReverseGeocode"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvRouteListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invroutelistener","abstract":[],"title":"InvRouteListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvRouteListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvRouteListener"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvRouteListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvReRouteType":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invreroutetype","abstract":[{"type":"text","text":"Route re-search types for navigation rerouting scenarios."}],"title":"InvReRouteType","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReRouteType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvReRouteType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvReRouteType"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/ObjectiveC":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ObjectiveC","url":"\/documentation\/inavinavigationsdk\/objectivec","type":"topic","title":"ObjectiveC","role":"collection","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapMarkerOption":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapMarkerOption","url":"\/documentation\/inavinavigationsdk\/invmapmarkeroption","type":"topic","title":"InvMapMarkerOption","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapMarkerOption","kind":"identifier"}],"navigatorTitle":[{"text":"InvMapMarkerOption","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/ShapeIDHelper":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/shapeidhelper","abstract":[],"title":"ShapeIDHelper","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ShapeIDHelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ShapeIDHelper"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ShapeIDHelper"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSearchResultType":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invsearchresulttype","abstract":[],"title":"InvSearchResultType","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchResultType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvSearchResultType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvSearchResultType"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvChargingPark":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvChargingPark","url":"\/documentation\/inavinavigationsdk\/invchargingpark","type":"topic","title":"InvChargingPark","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvChargingPark"}],"navigatorTitle":[{"kind":"identifier","text":"InvChargingPark"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvEntryPoint":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvEntryPoint","kind":"identifier"}],"navigatorTitle":[{"text":"InvEntryPoint","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/inventrypoint","title":"InvEntryPoint","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvEntryPoint","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvCategory":{"title":"InvCategory","url":"\/documentation\/inavinavigationsdk\/invcategory","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCategory","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvCategory"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvCategory"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvStatusListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invstatuslistener","abstract":[],"title":"InvStatusListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvStatusListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvStatusListener"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvStatusListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvViewport":{"title":"InvViewport","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvViewport","url":"\/documentation\/inavinavigationsdk\/invviewport","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvViewport","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvViewport","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvReverseGeocodeAddress":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocodeAddress","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/invreversegeocodeaddress","type":"topic","title":"InvReverseGeocodeAddress","role":"symbol","abstract":[{"type":"text","text":"Individual address result from reverse geocoding."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvReverseGeocodeAddress","kind":"identifier"}],"navigatorTitle":[{"text":"InvReverseGeocodeAddress","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvUIComponent":{"url":"\/documentation\/inavinavigationsdk\/invuicomponent","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvUIComponent","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvUIComponent","kind":"identifier"}],"navigatorTitle":[{"text":"InvUIComponent","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"UI component visibility control enum."}],"title":"InvUIComponent"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/SearchStatus":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/searchstatus","abstract":[],"title":"SearchStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/SearchStatus","kind":"symbol","navigatorTitle":[{"text":"SearchStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchStatus","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvDataSourceInfo":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InvDataSourceInfo","kind":"identifier"}],"navigatorTitle":[{"text":"InvDataSourceInfo","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invdatasourceinfo","title":"InvDataSourceInfo","role":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvDataSourceInfo","kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InitStatus":{"url":"\/documentation\/inavinavigationsdk\/initstatus","abstract":[],"type":"topic","title":"InitStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InitStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InitStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InitStatus"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvReverseGeocodingListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invreversegeocodinglistener","abstract":[],"title":"InvReverseGeocodingListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReverseGeocodingListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvReverseGeocodingListener"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvReverseGeocodingListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvDataSources":{"kind":"symbol","navigatorTitle":[{"text":"InvDataSources","kind":"identifier"}],"title":"InvDataSources","url":"\/documentation\/inavinavigationsdk\/invdatasources","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvDataSources","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvDataSources","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSearchListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invsearchlistener","abstract":[],"title":"InvSearchListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvSearchListener"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvSearchListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvLonLatListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invlonlatlistener","abstract":[],"title":"InvLonLatListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvLonLatListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvLonLatListener"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvLonLatListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/MapMoveStatus":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/mapmovestatus","abstract":[],"title":"MapMoveStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapMoveStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MapMoveStatus"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapMoveStatus"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvReqSearch":{"kind":"symbol","navigatorTitle":[{"text":"InvReqSearch","kind":"identifier"}],"title":"InvReqSearch","url":"\/documentation\/inavinavigationsdk\/invreqsearch","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvReqSearch","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvReqSearch","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"url":"\/documentation\/inavinavigationsdk","title":"iNaviNavigationSdk","role":"collection","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/NaviSDKVersionString":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/navisdkversionstring","abstract":[{"type":"text","text":"Project version string for NaviSDK."}],"title":"NaviSDKVersionString","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionString","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NaviSDKVersionString"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"NaviSDKVersionString"},{"kind":"text","text":": <<error type>>"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/MapModeStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MapModeStatus"}],"navigatorTitle":[{"kind":"identifier","text":"MapModeStatus"}],"url":"\/documentation\/inavinavigationsdk\/mapmodestatus","title":"MapModeStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/MapModeStatus","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvNameLocale":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invnamelocale","abstract":[],"title":"InvNameLocale","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvNameLocale","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvNameLocale"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvNameLocale"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvTimeZoneInfo":{"url":"\/documentation\/inavinavigationsdk\/invtimezoneinfo","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimeZoneInfo","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvTimeZoneInfo","kind":"identifier"}],"navigatorTitle":[{"text":"InvTimeZoneInfo","kind":"identifier"}],"role":"symbol","title":"InvTimeZoneInfo","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvIntersectionDetail":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvIntersectionDetail","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/invintersectiondetail","type":"topic","title":"InvIntersectionDetail","role":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvIntersectionDetail","kind":"identifier"}],"navigatorTitle":[{"text":"InvIntersectionDetail","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/AtomicUInt":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/atomicuint","abstract":[],"title":"AtomicUInt","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/AtomicUInt","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AtomicUInt"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AtomicUInt"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvPoi":{"url":"\/documentation\/inavinavigationsdk\/invpoi","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvPoi","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvPoi","kind":"identifier"}],"navigatorTitle":[{"text":"InvPoi","kind":"identifier"}],"role":"symbol","title":"InvPoi","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvGeometryInfo":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvGeometryInfo","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"InvGeometryInfo"}],"url":"\/documentation\/inavinavigationsdk\/invgeometryinfo","title":"InvGeometryInfo","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeometryInfo","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSearchResult":{"title":"InvSearchResult","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchResult","url":"\/documentation\/inavinavigationsdk\/invsearchresult","abstract":[{"text":"Comprehensive geocoding and POI search result.","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvSearchResult","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvSearchResult","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvInitListener":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/invinitlistener","abstract":[],"title":"InvInitListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvInitListener","kind":"symbol","navigatorTitle":[{"text":"InvInitListener","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvInitListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/NaviSDKVersionNumber":{"title":"NaviSDKVersionNumber","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionNumber","url":"\/documentation\/inavinavigationsdk\/navisdkversionnumber","abstract":[{"text":"Project version number for NaviSDK.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NaviSDKVersionNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NaviSDKVersionNumber","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvAddressRanges":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvAddressRanges","kind":"identifier"}],"navigatorTitle":[{"text":"InvAddressRanges","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invaddressranges","title":"InvAddressRanges","role":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvAddressRanges","kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvQueryIntentDetails":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvQueryIntentDetails","kind":"identifier"}],"navigatorTitle":[{"text":"InvQueryIntentDetails","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invqueryintentdetails","title":"InvQueryIntentDetails","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvQueryIntentDetails","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/GeocodingStatus":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/geocodingstatus","abstract":[],"title":"GeocodingStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/GeocodingStatus","kind":"symbol","navigatorTitle":[{"text":"GeocodingStatus","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GeocodingStatus","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/RelatedPoi":{"url":"\/documentation\/inavinavigationsdk\/relatedpoi","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/RelatedPoi","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RelatedPoi","kind":"identifier"}],"navigatorTitle":[{"text":"RelatedPoi","kind":"identifier"}],"role":"symbol","title":"RelatedPoi","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapCode":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapCode","url":"\/documentation\/inavinavigationsdk\/invmapcode","type":"topic","title":"InvMapCode","role":"symbol","abstract":[{"type":"text","text":"Represents a decoded mapcode and its components."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapCode","kind":"identifier"}],"navigatorTitle":[{"text":"InvMapCode","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapMoveListener":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapMoveListener","kind":"identifier"}],"navigatorTitle":[{"text":"InvMapMoveListener","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invmapmovelistener","title":"InvMapMoveListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapMoveListener","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSummary":{"title":"InvSummary","url":"\/documentation\/inavinavigationsdk\/invsummary","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSummary","abstract":[{"type":"text","text":"Search response metadata and statistics."}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvSummary"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvSummary"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvClassification":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvClassification"}],"navigatorTitle":[{"kind":"identifier","text":"InvClassification"}],"url":"\/documentation\/inavinavigationsdk\/invclassification","title":"InvClassification","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvClassification","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapView":{"title":"InvMapView","url":"\/documentation\/inavinavigationsdk\/invmapview","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapView","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvMapView","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapViewMode":{"url":"\/documentation\/inavinavigationsdk\/invmapviewmode","abstract":[],"title":"InvMapViewMode","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapViewMode","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapViewMode","navigatorTitle":[{"text":"InvMapViewMode","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvBottomBtnEvent":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvBottomBtnEvent","kind":"identifier"}],"navigatorTitle":[{"text":"InvBottomBtnEvent","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invbottombtnevent","title":"InvBottomBtnEvent","role":"symbol","abstract":[{"text":"Defines button events from the bottom navigation view.","type":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBottomBtnEvent","kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvAddress":{"url":"\/documentation\/inavinavigationsdk\/invaddress","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvAddress","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvAddress","kind":"identifier"}],"navigatorTitle":[{"text":"InvAddress","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Complete geocoded address structure with hierarchical administrative divisions."}],"title":"InvAddress"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvRoutePtItem":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvRoutePtItem","kind":"identifier"}],"navigatorTitle":[{"text":"InvRoutePtItem","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invrouteptitem","title":"InvRoutePtItem","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvRoutePtItem","abstract":[{"type":"text","text":"Individual waypoint or route point definition."}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/RouteStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"RouteStatus"}],"navigatorTitle":[{"kind":"identifier","text":"RouteStatus"}],"url":"\/documentation\/inavinavigationsdk\/routestatus","title":"RouteStatus","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/RouteStatus","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapRouteColor":{"url":"\/documentation\/inavinavigationsdk\/invmaproutecolor","abstract":[],"title":"InvMapRouteColor","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvMapRouteColor"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapRouteColor","navigatorTitle":[{"kind":"identifier","text":"InvMapRouteColor"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvBottomEventListener":{"url":"\/documentation\/inavinavigationsdk\/invbottomeventlistener","abstract":[],"type":"topic","title":"InvBottomEventListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBottomEventListener","kind":"symbol","navigatorTitle":[{"text":"InvBottomEventListener","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvBottomEventListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvGeocodingListener":{"url":"\/documentation\/inavinavigationsdk\/invgeocodinglistener","abstract":[],"type":"topic","title":"InvGeocodingListener","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeocodingListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvGeocodingListener"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InvGeocodingListener"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvTimeRange":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvTimeRange"}],"title":"InvTimeRange","url":"\/documentation\/inavinavigationsdk\/invtimerange","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvTimeRange"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimeRange","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvQueryIntent":{"url":"\/documentation\/inavinavigationsdk\/invqueryintent","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvQueryIntent","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvQueryIntent"}],"navigatorTitle":[{"kind":"identifier","text":"InvQueryIntent"}],"role":"symbol","title":"InvQueryIntent","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvBoundingBox":{"url":"\/documentation\/inavinavigationsdk\/invboundingbox","abstract":[{"type":"text","text":"Geographic bounding box defined by diagonal coordinates."}],"title":"InvBoundingBox","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InvBoundingBox","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBoundingBox","navigatorTitle":[{"kind":"identifier","text":"InvBoundingBox"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvConnector":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InvConnector"}],"title":"InvConnector","url":"\/documentation\/inavinavigationsdk\/invconnector","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvConnector"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvConnector","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvTimePoint":{"title":"InvTimePoint","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvTimePoint","url":"\/documentation\/inavinavigationsdk\/invtimepoint","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvTimePoint"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InvTimePoint"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/ReverseGeocodingStatus":{"title":"ReverseGeocodingStatus","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/ReverseGeocodingStatus","url":"\/documentation\/inavinavigationsdk\/reversegeocodingstatus","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ReverseGeocodingStatus","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"ReverseGeocodingStatus","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvMapTheme":{"url":"\/documentation\/inavinavigationsdk\/invmaptheme","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapTheme","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvMapTheme","kind":"identifier"}],"navigatorTitle":[{"text":"InvMapTheme","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Map theme configuration for day\/night modes."}],"title":"InvMapTheme"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvCoordinate":{"title":"InvCoordinate","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvCoordinate","url":"\/documentation\/inavinavigationsdk\/invcoordinate","abstract":[],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvCoordinate","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvCoordinate","kind":"identifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvNaviLocation":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InvNaviLocation"}],"navigatorTitle":[{"kind":"identifier","text":"InvNaviLocation"}],"url":"\/documentation\/inavinavigationsdk\/invnavilocation","title":"InvNaviLocation","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvNaviLocation","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvGeocode":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvGeocode","kind":"identifier"}],"navigatorTitle":[{"text":"InvGeocode","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/invgeocode","title":"InvGeocode","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvGeocode","abstract":[{"text":"Complete geocoding search response structure.","type":"text"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"navigatorTitle":[{"text":"InaviController","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","title":"InaviController","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","abstract":[],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvBrand":{"url":"\/documentation\/inavinavigationsdk\/invbrand","abstract":[],"title":"InvBrand","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvBrand","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvBrand","navigatorTitle":[{"text":"InvBrand","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSearchItem":{"url":"\/documentation\/inavinavigationsdk\/invsearchitem","abstract":[{"text":"Individual search result item for location search.","type":"text"}],"title":"InvSearchItem","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvSearchItem","kind":"identifier"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSearchItem","navigatorTitle":[{"text":"InvSearchItem","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InvSimpleSearchBar":{"title":"InvSimpleSearchBar","url":"\/documentation\/inavinavigationsdk\/invsimplesearchbar","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSimpleSearchBar","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InvSimpleSearchBar","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"InvSimpleSearchBar","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvMapView","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InvSimpleSearchBar"],"generated":true,"anchor":"Classes","title":"Classes"},{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionNumber","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/NaviSDKVersionString"],"generated":true,"anchor":"Variables","title":"Variables"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionString\/title","value":"NaviSDKVersionString","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionString\/fragments","value":[{"text":"NaviSDKVersionString","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionNumber\/title","value":"NaviSDKVersionNumber","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1NaviSDKVersionNumber\/fragments","value":[{"text":"NaviSDKVersionNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/title","value":"InvMapView","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/fragments","value":[{"text":"InvMapView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvMapView\/navigatorTitle","value":[{"text":"InvMapView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","value":"InaviController","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","value":[{"text":"InaviController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","value":[{"text":"InaviController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/title","value":"InvSimpleSearchBar","op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/fragments","value":[{"text":"InvSimpleSearchBar","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InvSimpleSearchBar\/navigatorTitle","value":[{"text":"InvSimpleSearchBar","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}