{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/inavinavigationsdk\/inavicontroller"]}],"hierarchy":{"paths":[["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/init()"],"anchor":"Initializers","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/addMapIcon(mapMarkerOption:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/cancelRoute()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/checkIsNight()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/forceHideMapComponent(componentID:hide:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getCurrentPosition()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getMapViewMode()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getOrbisLogDrive()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getSearchItem()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/isSetNaviBottomViewEventListener()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/moveOrbisSimulStep(bIsForward:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/naviInitialize(viewController:mapContainer:listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIcon(markerId:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIconAll()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeNaviBottomViewEventListener()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestGeocoding(address:onGeoCodingListener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestOrbisReRoute(reRouteType:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestReverseGeocoding(coordinate:onReverseGeocodingListener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runGuidance(searchItem:routeID:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runGuidanceFromRouteInfo(routeID:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runRoute(start:end:via:listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runSearch(req:listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runSimulGuidance(routeID:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setBottomButtonEvent(bottomBtnEvent:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapClickListener(listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapEnableRotate(enable:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapLevel(level:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapModeListener(listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapMoveChangedListener(listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapPadding(bottom:left:right:top:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapPosition(latitude:longitude:angle:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapRouteColor(color:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapTheme(theme:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapViewMode(mode:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setNaviBottomViewEventListener(listener:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setOrbisSimulSpeed(nSpeed:)","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/showSearchView()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/showTotalRouteInfoView()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/startOrbisSimulGuide()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/stopOrbisSimulGuide()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/zoomIn()","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/zoomOut()"],"anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/shared"],"anchor":"Type-Properties","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CLLocationManagerDelegate","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ","doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","title":"InaviController","modules":[{"name":"iNaviNavigationSdk"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@iNaviNavigationSdk@objc(cs)InaviController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InaviController","kind":"identifier"}],"navigatorTitle":[{"text":"InaviController","kind":"identifier"}]},"references":{"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/zoomIn()":{"type":"topic","abstract":[{"type":"text","text":"Performs a map zoom-in."},{"type":"text","text":" "},{"type":"text","text":"Zooms in one level from the current level."}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/zoomin()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/zoomIn()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomIn"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","title":"zoomIn()"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s7CVarArgP","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/getOrbisLogDrive()":{"title":"getOrbisLogDrive()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getOrbisLogDrive()","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Gets whether log driving is enabled."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getOrbisLogDrive"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/getorbislogdrive()"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/requestGeocoding(address:onGeoCodingListener:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestGeocoding"},{"kind":"text","text":"("},{"kind":"externalParam","text":"address"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"onGeoCodingListener"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk15GeocodingStatusO","text":"GeocodingStatus"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"text":"Calls the Geocoding API for the requested address to get location information.","type":"text"}],"title":"requestGeocoding(address:onGeoCodingListener:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestGeocoding(address:onGeoCodingListener:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/requestgeocoding(address:ongeocodinglistener:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setOrbisSimulSpeed(nSpeed:)":{"kind":"symbol","title":"setOrbisSimulSpeed(nSpeed:)","type":"topic","role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setOrbisSimulSpeed(nSpeed:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setorbissimulspeed(nspeed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setOrbisSimulSpeed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nSpeed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/requestReverseGeocoding(coordinate:onReverseGeocodingListener:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestReverseGeocoding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"coordinate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvCoordinate","preciseIdentifier":"s:18iNaviNavigationSdk13InvCoordinateV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"onReverseGeocodingListener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ReverseGeocodingStatus","preciseIdentifier":"s:18iNaviNavigationSdk22ReverseGeocodingStatusO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/requestreversegeocoding(coordinate:onreversegeocodinglistener:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestReverseGeocoding(coordinate:onReverseGeocodingListener:)","kind":"symbol","role":"symbol","abstract":[{"text":"Calls the ReverseGeocoding API for the requested coordinates to get address information.","type":"text"}],"type":"topic","title":"requestReverseGeocoding(coordinate:onReverseGeocodingListener:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/removeMapIconAll()":{"kind":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/removemapiconall()","abstract":[{"text":"Removes all markers added to the map at once.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeMapIconAll","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","title":"removeMapIconAll()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIconAll()","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapModeListener(listener:)":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapModeListener(listener:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapmodelistener(listener:)","abstract":[{"text":"Sets the map mode listener.","type":"text"}],"kind":"symbol","title":"setMapModeListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapModeListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"MapModeStatus","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk13MapModeStatusO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol","type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/getMapViewMode()":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getMapViewMode()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getMapViewMode","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"InvMapViewMode","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk14InvMapViewModeO"}],"abstract":[{"text":"Returns the current map view mode.","type":"text"}],"role":"symbol","title":"getMapViewMode()","type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/getmapviewmode()","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapClickListener(listener:)":{"role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapClickListener(listener:)","title":"setMapClickListener(listener:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapclicklistener(listener:)","abstract":[{"text":"Sets the map click event listener.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapClickListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"InvCoordinate","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk13InvCoordinateV"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/zoomOut()":{"title":"zoomOut()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zoomOut","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"text":"Performs a map zoom-out.","type":"text"},{"text":" ","type":"text"},{"text":"Zooms out one level from the current level.","type":"text"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/zoomout()","type":"topic","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/zoomOut()"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/naviInitialize(viewController:mapContainer:listener:)":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/naviInitialize(viewController:mapContainer:listener:)","role":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/naviinitialize(viewcontroller:mapcontainer:listener:)","type":"topic","abstract":[{"type":"text","text":"Performs the overall initialization of the SDK."}],"title":"naviInitialize(viewController:mapContainer:listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"naviInitialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"viewController","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":", ","kind":"text"},{"text":"mapContainer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"InitStatus","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk10InitStatusO"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/startOrbisSimulGuide()":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/startorbissimulguide()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/startOrbisSimulGuide()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startOrbisSimulGuide","kind":"identifier"},{"text":"()","kind":"text"}],"title":"startOrbisSimulGuide()","role":"symbol","abstract":[],"type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapLevel(level:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapLevel"},{"kind":"text","text":"("},{"kind":"externalParam","text":"level"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[{"text":"Sets the map zoom level.","type":"text"}],"role":"symbol","title":"setMapLevel(level:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapLevel(level:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmaplevel(level:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/init()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/init()","title":"init()","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/cancelRoute()":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/cancelroute()","title":"cancelRoute()","abstract":[{"text":"Cancels the ongoing route guidance.","type":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/cancelRoute()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelRoute"},{"kind":"text","text":"()"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)NSObject","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/forceHideMapComponent(componentID:hide:)":{"type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/forceHideMapComponent(componentID:hide:)","kind":"symbol","title":"forceHideMapComponent(componentID:hide:)","role":"symbol","abstract":[{"type":"text","text":"Forcibly sets the visibility state of a specific UI component."}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/forcehidemapcomponent(componentid:hide:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forceHideMapComponent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"componentID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:18iNaviNavigationSdk14InvUIComponentO","text":"InvUIComponent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"hide","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/runRoute(start:end:via:listener:)":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/runroute(start:end:via:listener:)","title":"runRoute(start:end:via:listener:)","role":"symbol","abstract":[{"text":"Runs a route calculation.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"runRoute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"start"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvRoutePtItem","preciseIdentifier":"s:18iNaviNavigationSdk14InvRoutePtItemV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"end"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvRoutePtItem","preciseIdentifier":"s:18iNaviNavigationSdk14InvRoutePtItemV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"via"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"InvRoutePtItem","preciseIdentifier":"s:18iNaviNavigationSdk14InvRoutePtItemV"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"RouteStatus","preciseIdentifier":"s:18iNaviNavigationSdk11RouteStatusO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runRoute(start:end:via:listener:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/removeMapIcon(markerId:)":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/removemapicon(markerid:)","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeMapIcon(markerId:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeMapIcon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"markerId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeMapIcon(markerId:)","abstract":[{"type":"text","text":"Removes a marker added to the map using its identifier ([markerId])."}],"kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/getSearchItem()":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/getsearchitem()","title":"getSearchItem()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getSearchItem()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getSearchItem","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"InvSearchItem","preciseIdentifier":"s:18iNaviNavigationSdk13InvSearchItemV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk":{"kind":"symbol","type":"topic","role":"collection","title":"iNaviNavigationSdk","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk","abstract":[],"url":"\/documentation\/inavinavigationsdk"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/shared":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"InaviController","kind":"typeIdentifier","preciseIdentifier":"c:@M@iNaviNavigationSdk@objc(cs)InaviController"}],"role":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/shared","title":"shared","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/shared","type":"topic","kind":"symbol","abstract":[]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InaviController"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController","navigatorTitle":[{"kind":"identifier","text":"InaviController"}],"type":"topic","abstract":[],"url":"\/documentation\/inavinavigationsdk\/inavicontroller","title":"InaviController","kind":"symbol","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapTheme(theme:)":{"type":"topic","abstract":[{"text":"Sets the desired map theme (Automatic, Day, Night).","type":"text"}],"title":"setMapTheme(theme:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvMapTheme","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk11InvMapThemeO"},{"text":")","kind":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapTheme(theme:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmaptheme(theme:)","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SQ"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/getCurrentPosition()":{"abstract":[{"type":"text","text":"Returns the current position."}],"title":"getCurrentPosition()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/getcurrentposition()","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/getCurrentPosition()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getCurrentPosition","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:18iNaviNavigationSdk03InvA8LocationV","text":"InvNaviLocation","kind":"typeIdentifier"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/checkIsNight()":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/checkIsNight()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/checkisnight()","title":"checkIsNight()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIsNight"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/runGuidance(searchItem:routeID:)":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runGuidance(searchItem:routeID:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runGuidance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"searchItem","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvSearchItem","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk13InvSearchItemV"},{"text":", ","kind":"text"},{"text":"routeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Starts guidance for a calculated route.","type":"text"}],"role":"symbol","title":"runGuidance(searchItem:routeID:)","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/runguidance(searchitem:routeid:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/runSimulGuidance(routeID:)":{"type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/runsimulguidance(routeid:)","role":"symbol","title":"runSimulGuidance(routeID:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runSimulGuidance","kind":"identifier"},{"text":"(","kind":"text"},{"text":"routeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runSimulGuidance(routeID:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapViewMode(mode:)":{"title":"setMapViewMode(mode:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapviewmode(mode:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapViewMode(mode:)","abstract":[{"text":"Sets the map view mode.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapViewMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvMapViewMode","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk14InvMapViewModeO"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/runSearch(req:listener:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runSearch(req:listener:)","role":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/runsearch(req:listener:)","abstract":[{"type":"text","text":"POI Search"}],"title":"runSearch(req:listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"runSearch"},{"kind":"text","text":"("},{"kind":"externalParam","text":"req"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvReqSearch","preciseIdentifier":"s:18iNaviNavigationSdk12InvReqSearchV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SearchStatus","preciseIdentifier":"s:18iNaviNavigationSdk12SearchStatusO"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapRouteColor(color:)":{"title":"setMapRouteColor(color:)","abstract":[{"text":"Changes the route line color.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapRouteColor"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvMapRouteColor","preciseIdentifier":"s:18iNaviNavigationSdk16InvMapRouteColorO"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapRouteColor(color:)","type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmaproutecolor(color:)","kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/moveOrbisSimulStep(bIsForward:)":{"role":"symbol","abstract":[],"title":"moveOrbisSimulStep(bIsForward:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/moveorbissimulstep(bisforward:)","kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/moveOrbisSimulStep(bIsForward:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moveOrbisSimulStep","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bIsForward","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapMoveChangedListener(listener:)":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapmovechangedlistener(listener:)","title":"setMapMoveChangedListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapMoveChangedListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:18iNaviNavigationSdk13MapMoveStatusO","text":"MapMoveStatus","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapMoveChangedListener(listener:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Sets an event listener that is called when the map is moved."}],"type":"topic"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setNaviBottomViewEventListener(listener:)":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setNaviBottomViewEventListener(listener:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setNaviBottomViewEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"InvBottomBtnEvent","preciseIdentifier":"s:18iNaviNavigationSdk17InvBottomBtnEventO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"When registering a BottomViewEvent, you can override the default behavior","type":"text"},{"text":" ","type":"text"},{"text":"and replace it with a custom action from the 3rd party app.","type":"text"}],"kind":"symbol","title":"setNaviBottomViewEventListener(listener:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setnavibottomvieweventlistener(listener:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/showTotalRouteInfoView()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showTotalRouteInfoView","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Displays the complete route information screen."}],"title":"showTotalRouteInfoView()","type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/showtotalrouteinfoview()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/showTotalRouteInfoView()","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/SH"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setBottomButtonEvent(bottomBtnEvent:)":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setBottomButtonEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bottomBtnEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"InvBottomBtnEvent","preciseIdentifier":"s:18iNaviNavigationSdk17InvBottomBtnEventO"},{"kind":"text","text":")"}],"title":"setBottomButtonEvent(bottomBtnEvent:)","abstract":[{"text":"A function to set an event from the BottomViewModel.","type":"text"}],"type":"topic","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setBottomButtonEvent(bottomBtnEvent:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setbottombuttonevent(bottombtnevent:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/addMapIcon(mapMarkerOption:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addMapIcon","kind":"identifier"},{"text":"(","kind":"text"},{"text":"mapMarkerOption","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvMapMarkerOption","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk18InvMapMarkerOptionV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Adds a map icon (marker) at the specified location.","type":"text"}],"type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/addmapicon(mapmarkeroption:)","title":"addMapIcon(mapMarkerOption:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/addMapIcon(mapMarkerOption:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/runGuidanceFromRouteInfo(routeID:)":{"title":"runGuidanceFromRouteInfo(routeID:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/runguidancefromrouteinfo(routeid:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"runGuidanceFromRouteInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"routeID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/runGuidanceFromRouteInfo(routeID:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapEnableRotate(enable:)":{"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapenablerotate(enable:)","kind":"symbol","title":"setMapEnableRotate(enable:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapEnableRotate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"enable"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"Enables or disables the map rotation gesture."}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapEnableRotate(enable:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/stopOrbisSimulGuide()":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/stopOrbisSimulGuide()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopOrbisSimulGuide","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/inavinavigationsdk\/inavicontroller\/stoporbissimulguide()","type":"topic","kind":"symbol","role":"symbol","title":"stopOrbisSimulGuide()"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/removeNaviBottomViewEventListener()":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/removeNaviBottomViewEventListener()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeNaviBottomViewEventListener"},{"kind":"text","text":"()"}],"title":"removeNaviBottomViewEventListener()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/removenavibottomvieweventlistener()","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"A function to remove the interface registered by the 3rd party app","type":"text"},{"text":" ","type":"text"},{"text":"in order to operate the features provided by the BottomView.","type":"text"}]},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/requestOrbisReRoute(reRouteType:)":{"kind":"symbol","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/requestOrbisReRoute(reRouteType:)","type":"topic","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/requestorbisreroute(reroutetype:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestOrbisReRoute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reRouteType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"InvReRouteType","kind":"typeIdentifier","preciseIdentifier":"s:18iNaviNavigationSdk14InvReRouteTypeO"},{"text":")","kind":"text"}],"title":"requestOrbisReRoute(reRouteType:)","role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/showSearchView()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showSearchView","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","title":"showSearchView()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/showsearchview()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/showSearchView()","abstract":[{"text":"Displays the search screen for destination search.","type":"text"}],"kind":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapPadding(bottom:left:right:top:)":{"title":"setMapPadding(bottom:left:right:top:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setMapPadding","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapPadding(bottom:left:right:top:)","kind":"symbol","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmappadding(bottom:left:right:top:)","abstract":[{"type":"text","text":"Sets the padding for the map view."}],"role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/isSetNaviBottomViewEventListener()":{"kind":"symbol","abstract":[{"text":"A function to check if a BottomViewListener is registered from a 3rd party app.","type":"text"}],"title":"isSetNaviBottomViewEventListener()","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/issetnavibottomvieweventlistener()","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/isSetNaviBottomViewEventListener()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isSetNaviBottomViewEventListener","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/documentation/iNaviNavigationSdk/InaviController/setMapPosition(latitude:longitude:angle:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setMapPosition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"latitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"longitude"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"angle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Moves the map’s position based on the specified coordinates."}],"role":"symbol","title":"setMapPosition(latitude:longitude:angle:)","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/setMapPosition(latitude:longitude:angle:)","url":"\/documentation\/inavinavigationsdk\/inavicontroller\/setmapposition(latitude:longitude:angle:)"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://iNaviSys.NaviSDKIOS.NaviSDK/objc(pl)CLLocationManagerDelegate":{"identifier":"doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CLLocationManagerDelegate","title":"CLLocationManagerDelegate","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"InaviController","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"InaviController"}],"path":"\/metadata\/fragments"},{"value":[{"text":"InaviController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/init()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/documentation\/iNaviNavigationSdk\/InaviController\/shared"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/iNaviSys.NaviSDKIOS.NaviSDK\/objc(pl)CLLocationManagerDelegate"],"kind":"relationships","title":"Conforms To"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InaviController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1init()\/fragments","op":"replace"},{"value":"shared","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1shared\/title","op":"replace"},{"value":[{"kind":"identifier","text":"shared"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController~1shared\/fragments","op":"replace"},{"value":"InaviController","path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"InaviController"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/fragments","op":"replace"},{"value":[{"text":"InaviController","kind":"identifier"}],"path":"\/references\/doc:~1~1iNaviSys.NaviSDKIOS.NaviSDK~1documentation~1iNaviNavigationSdk~1InaviController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}